# Generated by Django 4.2.2 on 2023-06-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_time_listing_status_listing_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.TextField(blank=True, default=''),
        ),
    ]
